In [1]:
%autosave 60

Autosaving every 60 seconds


In [2]:
import string
string.ascii_letters + string.digits
string.printable

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [17]:
# class for the dataset:
import torch
# class for text-datasets
# Jama, NEJM and lancet
from torch.utils.data import Dataset, DataLoader
import unicodedata
class TextDataset(Dataset):

    SPECIAL_CHARS = [None, "\n"]
    def __len__(self):
        return len(self.total_examples)
        pass
 
    # generates tensors for the vocab
    # i.e. assigns a number to each character
    # Q: possible to do one-pass?
    def make_vocab(self):
        
        self.char2index = {}
        self.index2char = {}
        index = 0
        with open(self.text_file) as file:
            for line in file:
                for char in line:
                    if char not in self.char2index:
                        self.char2index[char] = index
                        self.index2char[index]  = char
                        index+=1
        
        for char in self.SPECIAL_CHARS:
#             print("this is the char")
            if char not in self.char2index:
                self.char2index[char] = index
                self.index2char[index] = char
                index += 1
        
        print(self.char2index[None])
        # potentially need to add 2 for the None and \n characters
        self.vocab_size = len(self.char2index)
    
    # this allows the model to handle all possible strings passed into it!!
    def full_vocab(self):
        self.char2index = {}
        self.index2char = {}
        index = 0
        all_letters = string.printable 
        for char in all_letters:
            if char not in self.char2index:
                self.char2index[char] = index
                self.index2char[index]  = char
                index+=1
                
        for char in self.SPECIAL_CHARS:
#             print("this is the char")
            if char not in self.char2index:
                self.char2index[char] = index
                self.index2char[index] = char
                index += 1
                
        self.vocab_size = len(self.char2index)   
        
        
    
    
    def generate_tensor_for_char(self, char):
        temp = torch.zeros(1, self.vocab_size)
        temp[0][self.char2index[char]] = 1 
        return temp

#     def generate_char_from_tensor(self, char):
#         temp = torch.zeros(self.vocab_size, 1)
#         temp[self.char2index[char]][0] = 1 
#         return temp
    def lineToTensor(self,line):
        tensor = torch.zeros(len(line), 1, self.vocab_size)
#         print(line)
        for li, letter in enumerate(line):
            tensor[li][0][self.char2index[letter]] = 1
        return tensor
    
    # wrap the lines!
    def train_example_builder(self, line):
        tensor = torch.zeros(len(line), 1, self.vocab_size)
        for li, letter in enumerate(line):
            tensor[li][0][self.char2index[letter]] = 1
        return tensor
      
#     could do more of a common build api
    def get_None_tensor(self):
        tensor = torch.zeros(1, 1, self.vocab_size)
        tensor[0][0][self.char2index[None]] = 1
        return tensor
    
    def list_to_tensor(self, input_list):
        tensor = torch.zeros(len(input_list), 1, self.vocab_size)
        for elt in input_list:
            tensor[li][0][self.char2index[letter]] = 1
            
#     def get_training_pair(self, line):
        
        
    
    def get_new_line_tensor(self):
        tensor = torch.zeros(1, 1, self.vocab_size)
        tensor[0][0][self.char2index["\n"]] = 1
        return tensor

        
#         tensor[li][0][self.char2index[letter]] 
#         temp 
    def unicodeToAscii(self,s):
        return ''.join(
            c for c in unicodedata.normalize('NFD', s)
            if unicodedata.category(c) != 'Mn'
            and c in self.char2index
        )

#     OK, so given the raw lines of text, then we want to get it! (but it is json, so we need to process it anyways)
# 
    def get_test_split(self):
        return self.test_split
        pass
    def __init__(self, text_files,  convert_to_ascii = True):
        self.string = string
        self.text_files = text_files

        self.training_examples = []

        total_inputs = []
        total_outputs = []
        
#         make the vocab
        self.full_vocab()
    
        from tqdm import tqdm
        for target_class, file_name in enumerate(tqdm(text_files)):
            with open(file_name,  encoding="utf8") as file:
                for counter, raw_line in enumerate(file):
#                     if counter > 500:
#                         break

                    line = self.unicodeToAscii(raw_line) if convert_to_ascii else raw_line
                    line = line[0:139]
                    # zero pad to start


    #                 think about how to make this a vector or tensor line! 
    #                 print()

    #                 inputs = self.get_None_tensor() + line_to_tensor(line)
    #                 inputs = [None] + [x for x in line]
                    inputs = self.lineToTensor([None] + [x for x in line])

                    targets = torch.zeros((1,4))  # we need a 0 as well!
                    targets[0,target_class] = 1
                
#                     print(targets)

                    # append: will be a list of list (of lines)
                    # extend: will be a list of lines
                    total_inputs.append(inputs)
                    total_outputs.append(targets)

        assert len(total_inputs) == len(total_outputs)
        
        import random
        
        
        # this is now a LIST of lists!
        self.total_examples = list(zip(total_inputs, total_outputs))
        random.shuffle(self.total_examples)
        train_split = self.total_examples[0:32000]
        test_split = self.total_examples[32000:-1] #all the rest are test exampels
        print(len(train_split))
        print(len(test_split))
        self.test_split = test_split
        self.total_examples = train_split
        


        #                 for char in line:
        # how many chars before the target? or all chars before the target?
        # so we simply pair up x with [x+1] i think
        # ok, and then we iterate them in the loader?
        #                     inputs = [x for x in ]
        #                     targets = []

        # we should also have some big list of entries 

        pass
    
    
    # ok, now let us just try adding the transforms
    # actually the transforms should take responsibility for all of the vocab stuff
    
    # number of items in the dataset. This involves a rather large computation!
    # we can either do a feed forward cllm in the style of bengio, or we can just 
    # do the RNN approach (as specified by Sean Robertson in his tutorial)

    # the indices should represent examples inside the list
    # one strange thing is the following: we need to precompute al the indices earlier, imo, and then simply return the list
    # at that element! (perhaps with some transforms!)
    def __getitem__(self, index):
        return self.total_examples[index]

        # build a list, return elements from that list? we need to internally keep track of some index
        pass



# ok, so it works now!

In [18]:
files = [r"reddit_data/Left-reduced",r"reddit_data/Center-reduced", 
        r"reddit_data/Right-reduced", r"reddit_data/Alt-reduced"]
abc = TextDataset( files, True)


#think about unicode issues



100%|██████████| 4/4 [00:28<00:00,  7.14s/it]


32000
8028


In [19]:
print(abc.char2index[None])

100


In [20]:
abc.get_test_split()

[(tensor([[[ 0.,  0.,  0.,  ...,  0.,  0.,  1.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          ...,
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]]]),
  tensor([[ 0.,  0.,  0.,  1.]])),
 (tensor([[[ 0.,  0.,  0.,  ...,  0.,  0.,  1.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          ...,
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]]]),
  tensor([[ 0.,  1.,  0.,  0.]])),
 (tensor([[[ 0.,  0.,  0.,  ...,  0.,  0.,  1.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          ...,
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ..

In [22]:
abc.test_split

[(tensor([[[ 0.,  0.,  0.,  ...,  0.,  0.,  1.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          ...,
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]]]),
  tensor([[ 0.,  0.,  0.,  1.]])),
 (tensor([[[ 0.,  0.,  0.,  ...,  0.,  0.,  1.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          ...,
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]]]),
  tensor([[ 0.,  1.,  0.,  0.]])),
 (tensor([[[ 0.,  0.,  0.,  ...,  0.,  0.,  1.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          ...,
  
          [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],
  
          [[ 0.,  0.,  0.,  ..

In [23]:
abc.generate_tensor_for_char("a")
# abc.index2char[2]
abc.lineToTensor("abcd")
    

tensor([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
  

In [24]:


for (a,b) in abc:
    pass
#     this should give two lines/tests
#     print(a,b)
#     print()
    
#     realistically, we should also have it as tensors/vectors
# finally, we should also have some way where we run the rnn forward and 
#  iteratoring over the set, does not consume the elements! It is not a genertor! Rather, we simply index into the elements we would like
for(a,b) in abc:
    pass
#     print("ok")

In [25]:
char_x = [None] + ["e"]

In [26]:
# ok, so now let's just do the stuff
# the RNN actually makes one-character over predictions! 
# rnn_forward is a utility function that does a lot of stuff
len(char_x)


2

In [27]:
# ok, so now we can start building the network that will process these!!
# simply: iterate the dataset, and run train on it, do the log likelihood and etc.

import torch.nn as nn
import torch.nn.functional as F
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size

        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        
        self.i2o = nn.Linear(input_size + hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, input, hidden):
        combined = torch.cat((input, hidden), 1)
        combined = F.relu(combined)
        hidden = self.i2h(combined)
        output = self.i2o(combined)
        output = self.softmax(output)
        return output, hidden

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)
    
n_hidden = 256


rnn = RNN(abc.vocab_size, n_hidden, 4) #since 4 categories

In [28]:
abc.lineToTensor("we")

tensor([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
  

In [29]:

# WE NEED THIS LINE TO RESET THE RNN!!
rnn = RNN(abc.vocab_size, n_hidden, 4)
learning_rate = 0.0005 # If you set this too high, it might explode. If too low, it might not learn
#  we had to set it a big lower to force convergence

import torch.optim as optim
optimizer = optim.Adam(rnn.parameters())

# returns the loss for a line

def train(input_tensor, target_tensor):
    
        
#     print(input_tensor)
#     print(input_tensor.shape)

#     print(target_tensor)

    optimizer.zero_grad()
    
#     print (input_tensor)
    
#     print("changed3")
#     print(input_tensor[1])
    criterion = nn.NLLLoss()    
    hidden = rnn.initHidden()
    loss = 0
    rnn.zero_grad()
#     print(input_tensor.size())
#     print(target_tensor[0])
#     print(target_tensor)
#     print(input_tensor.size()[0])
    
#     we want EVERYTHING to come and output a single value
    for i in range(input_tensor.size()[0]):
        output, hidden = rnn(input_tensor[i], hidden)
        
        
        
#         find where the one is:
# 
#         torch.tensor([all_categories.index(category)], dtype=torch.long)
    
    true_target_tensor = torch.tensor([torch.argmax(target_tensor)], dtype=torch.long)
    
#     true_target_tensor = target_tensor
#     print(output)
#     print(output.shape)
#     print(true_target_tensor)
#     print(true_target_tensor.shape)
# it needs a single max value interestingly!
#     Evaluate the loss on each character!
    
#     some "gradient clipping"; the loss has no effect in this case

    loss += criterion(output,true_target_tensor)
    loss.backward()
        
#         expects JUST a single target class:

#     print ("loss for i " + str(loss.item()))    
#         print()
# should be do the loss on each thing, or each batch! no, we should accumulate it! 
    loss_val = loss.item()
    if loss_val < 5:
        optimizer.step()
    else:
#         print("clipping")
#         print(loss_val)
        loss_val = 5
    
    # Add parameters' gradients to their values, multiplied by learning rate
#     for p in rnn.parameters():
#         p.data.add_(-learning_rate, p.grad.data)

    return output, loss_val

# why not run this just on all the tensors!! 

# then, we just call it with the dataset class, and then just iterate everything!!

In [30]:
abc.index2char[0]
abc.index2char[1]

abc.char2index["A"]

# ok some weird stuff here...


36

In [31]:
# for (x,y) in abc:
#     print(y)


In [ ]:
# del rnn
# rnn = RNN(abc.vocab_size, n_hidden, abc.vocab_size)

epoch_loss = 0
# loss every k iters
# 
total_loss = 0
total_length  = 0
epoch_length = 0
other_loss = 0

from tqdm import tqdm
num_epochs = 10
for k in range(num_epochs ):
    
    for i,(x,y) in enumerate(tqdm(abc)):
    #     print(x)
    #     print(x)
    #     print(y)
        _, loss = train(x,y)
        epoch_loss += loss
        epoch_length += x.size()[0]
        total_loss += loss
        total_length += x.size()[0]
        other_loss +=loss
#         print(loss)
    #     print(i)
    #     abc = i
        if i % 500 == 0:
            print ("loss for {} is {}".format(i,other_loss/500))
            other_loss = 0
#         break

    
    print("epoch {} loss is {}".format(k, epoch_loss/i))
    print("per character loss is {}".format(epoch_loss/epoch_length))
    epoch_loss = 0
    epoch_length = 0
#     ideally: we would be able to compute the quintile losses
    


  0%|          | 2/32000 [00:00<1:06:30,  8.02it/s]

loss for 0 is 0.0026472978591918946



  1%|▏         | 460/32000 [00:25<29:30, 17.82it/s]


  2%|▏         | 506/32000 [00:28<29:06, 18.03it/s]

loss for 500 is 1.3835966997146607



  3%|▎         | 978/32000 [00:52<27:54, 18.52it/s]


  3%|▎         | 1004/32000 [00:54<27:48, 18.58it/s]

loss for 1000 is 1.4930970847476275



  5%|▍         | 1505/32000 [01:17<26:16, 19.34it/s]

loss for 1500 is 1.3695705322027207



  6%|▋         | 2009/32000 [01:29<22:16, 22.44it/s]

loss for 2000 is 1.4665508666934222



  8%|▊         | 2501/32000 [01:41<20:00, 24.57it/s]


loss for 2500 is 1.3743485984802246


  9%|▉         | 3010/32000 [01:56<18:43, 25.81it/s]

loss for 3000 is 1.371062284231186



 11%|█         | 3481/32000 [02:20<19:09, 24.81it/s]


 11%|█         | 3505/32000 [02:21<19:14, 24.69it/s]

loss for 3500 is 1.3719205300807953



 12%|█▏        | 3960/32000 [02:45<19:30, 23.96it/s]


 13%|█▎        | 4005/32000 [02:47<19:29, 23.94it/s]

loss for 4000 is 1.3674381287097932



 14%|█▍        | 4454/32000 [03:10<19:36, 23.41it/s]


 14%|█▍        | 4508/32000 [03:12<19:32, 23.44it/s]

loss for 4500 is 1.3601937744617463



 16%|█▌        | 5003/32000 [03:34<19:18, 23.31it/s]

loss for 5000 is 1.3637036626338959



 17%|█▋        | 5489/32000 [03:57<19:07, 23.10it/s]


 17%|█▋        | 5504/32000 [03:58<19:08, 23.07it/s]

loss for 5500 is 1.3750032957792282



 19%|█▉        | 6003/32000 [04:20<18:47, 23.06it/s]

loss for 6000 is 1.3688812644481658



 20%|██        | 6488/32000 [04:43<18:33, 22.92it/s]


 20%|██        | 6506/32000 [04:43<18:31, 22.95it/s]

loss for 6500 is 1.3703225530385972



 22%|██▏       | 7007/32000 [05:06<18:13, 22.86it/s]

loss for 7000 is 1.3626054857969283



 23%|██▎       | 7503/32000 [05:28<17:53, 22.81it/s]

loss for 7500 is 1.3632799632549286



 25%|██▌       | 8001/32000 [05:50<17:31, 22.81it/s]

loss for 8000 is 1.3539768981933593



 26%|██▋       | 8470/32000 [06:13<17:17, 22.67it/s]


 27%|██▋       | 8503/32000 [06:15<17:17, 22.66it/s]

loss for 8500 is 1.3673197288513184



 28%|██▊       | 8976/32000 [06:38<17:01, 22.54it/s]


 28%|██▊       | 9007/32000 [06:39<17:00, 22.54it/s]

loss for 9000 is 1.3664635915756225



 30%|██▉       | 9480/32000 [07:02<16:43, 22.44it/s]


 30%|██▉       | 9504/32000 [07:03<16:41, 22.46it/s]

loss for 9500 is 1.36804429936409



 31%|███       | 9961/32000 [07:26<16:27, 22.32it/s]


 31%|███▏      | 10004/32000 [07:28<16:26, 22.31it/s]

loss for 10000 is 1.360469935297966



 33%|███▎      | 10456/32000 [07:51<16:10, 22.19it/s]


 33%|███▎      | 10502/32000 [07:53<16:10, 22.16it/s]

loss for 10500 is 1.3672006446123124



 34%|███▍      | 11005/32000 [08:15<15:44, 22.22it/s]

loss for 11000 is 1.3815925738811492



 36%|███▌      | 11485/32000 [08:36<15:23, 22.22it/s]


 36%|███▌      | 11510/32000 [08:37<15:21, 22.23it/s]

loss for 11500 is 1.3645219826698303



 37%|███▋      | 11994/32000 [09:00<15:01, 22.18it/s]


 38%|███▊      | 12000/32000 [09:01<15:01, 22.18it/s]

loss for 12000 is 1.371066287279129



 39%|███▉      | 12465/32000 [09:23<14:43, 22.10it/s]


 39%|███▉      | 12508/32000 [09:25<14:41, 22.10it/s]

loss for 12500 is 1.3722438523769378



 41%|████      | 12982/32000 [09:48<14:22, 22.05it/s]


 41%|████      | 13004/32000 [09:49<14:21, 22.05it/s]

loss for 13000 is 1.3636330416202544



 42%|████▏     | 13477/32000 [10:12<14:01, 22.01it/s]


 42%|████▏     | 13503/32000 [10:12<13:59, 22.03it/s]

loss for 13500 is 1.365566908955574



 44%|████▎     | 13981/32000 [10:36<13:39, 21.98it/s]


 44%|████▍     | 14007/32000 [10:37<13:38, 21.98it/s]

loss for 14000 is 1.3623049927949906



 45%|████▌     | 14503/32000 [10:57<13:13, 22.05it/s]

loss for 14500 is 1.3622512308359147



 47%|████▋     | 14949/32000 [11:21<12:56, 21.95it/s]


 47%|████▋     | 15005/32000 [11:23<12:53, 21.97it/s]

loss for 15000 is 1.347321015357971



 48%|████▊     | 15457/32000 [11:45<12:35, 21.90it/s]


 48%|████▊     | 15503/32000 [11:48<12:33, 21.89it/s]

loss for 15500 is 1.3697190010547637



 50%|████▉     | 15985/32000 [12:11<12:13, 21.84it/s]


 50%|█████     | 16005/32000 [12:12<12:12, 21.84it/s]

loss for 16000 is 1.3698116774559022



 52%|█████▏    | 16502/32000 [12:34<11:48, 21.88it/s]

loss for 16500 is 1.3609624878168105



 53%|█████▎    | 16974/32000 [12:56<11:27, 21.85it/s]


 53%|█████▎    | 17003/32000 [12:58<11:26, 21.84it/s]

loss for 17000 is 1.3620476964712143



 55%|█████▍    | 17473/32000 [13:22<11:07, 21.78it/s]


 55%|█████▍    | 17498/32000 [13:24<11:06, 21.76it/s]

loss for 17500 is 1.3497591235637665



 56%|█████▌    | 17932/32000 [13:46<10:48, 21.69it/s]


 56%|█████▋    | 18001/32000 [13:50<10:45, 21.68it/s]

loss for 18000 is 1.3688178887367248



 58%|█████▊    | 18442/32000 [14:13<10:27, 21.60it/s]


 58%|█████▊    | 18507/32000 [14:16<10:24, 21.60it/s]

loss for 18500 is 1.351040582537651



 59%|█████▉    | 18943/32000 [14:40<10:06, 21.52it/s]


 59%|█████▉    | 19004/32000 [14:43<10:03, 21.52it/s]

loss for 19000 is 1.3550917999744416



 61%|██████    | 19374/32000 [15:09<09:52, 21.30it/s]


 61%|██████    | 19503/32000 [15:18<09:48, 21.22it/s]

loss for 19500 is 1.3693248965740203



 62%|██████▏   | 19904/32000 [15:42<09:32, 21.11it/s]


 63%|██████▎   | 20004/32000 [15:45<09:26, 21.16it/s]

loss for 20000 is 1.3597800941467286



 64%|██████▍   | 20505/32000 [15:58<08:57, 21.39it/s]

loss for 20500 is 1.3658289028406143



 66%|██████▌   | 21004/32000 [16:12<08:29, 21.59it/s]

loss for 21000 is 1.3510239032506943



 67%|██████▋   | 21506/32000 [16:32<08:04, 21.66it/s]

loss for 21500 is 1.3513965775966645



 69%|██████▊   | 21981/32000 [16:55<07:42, 21.65it/s]


 69%|██████▉   | 22002/32000 [16:56<07:41, 21.65it/s]

loss for 22000 is 1.3607872718572616



 70%|███████   | 22465/32000 [17:18<07:20, 21.64it/s]


 70%|███████   | 22504/32000 [17:20<07:18, 21.64it/s]

loss for 22500 is 1.3540982954502105



 72%|███████▏  | 22967/32000 [17:43<06:58, 21.60it/s]


 72%|███████▏  | 22999/32000 [17:44<06:56, 21.60it/s]

loss for 23000 is 1.3644361716508866



 73%|███████▎  | 23448/32000 [18:08<06:36, 21.55it/s]


 73%|███████▎  | 23505/32000 [18:10<06:34, 21.55it/s]

loss for 23500 is 1.3598214910030364



 75%|███████▌  | 24007/32000 [18:32<06:10, 21.58it/s]

loss for 24000 is 1.3417710583209992



 77%|███████▋  | 24503/32000 [18:55<05:47, 21.58it/s]

loss for 24500 is 1.3590699002742768



 78%|███████▊  | 24969/32000 [19:17<05:26, 21.57it/s]


 78%|███████▊  | 25006/32000 [19:19<05:24, 21.56it/s]

loss for 25000 is 1.3458218275308609



 79%|███████▉  | 25436/32000 [19:42<05:05, 21.51it/s]


 80%|███████▉  | 25502/32000 [19:45<05:02, 21.51it/s]

loss for 25500 is 1.3544564808607102



 81%|████████  | 25988/32000 [20:08<04:39, 21.51it/s]


 81%|████████▏ | 26002/32000 [20:08<04:38, 21.51it/s]

loss for 26000 is 1.3745914843082427



 83%|████████▎ | 26503/32000 [20:28<04:14, 21.57it/s]

loss for 26500 is 1.3632375065088271



 84%|████████▍ | 27005/32000 [20:50<03:51, 21.59it/s]

loss for 27000 is 1.3533125849962235



 86%|████████▌ | 27475/32000 [21:13<03:29, 21.57it/s]


 86%|████████▌ | 27505/32000 [21:15<03:28, 21.57it/s]

loss for 27500 is 1.3570358462333678



 88%|████████▊ | 28006/32000 [21:37<03:05, 21.58it/s]

loss for 28000 is 1.3614479904174805



 89%|████████▉ | 28483/32000 [22:00<02:43, 21.57it/s]


 89%|████████▉ | 28503/32000 [22:02<02:42, 21.56it/s]

loss for 28500 is 1.3827821085453034



 91%|█████████ | 28977/32000 [22:25<02:20, 21.54it/s]


 91%|█████████ | 29005/32000 [22:26<02:19, 21.54it/s]

loss for 29000 is 1.357492067694664



 92%|█████████▏| 29508/32000 [22:47<01:55, 21.57it/s]

loss for 29500 is 1.3692538043260574



 94%|█████████▎| 29995/32000 [23:10<01:32, 21.58it/s]


 94%|█████████▍| 30003/32000 [23:10<01:32, 21.58it/s]

loss for 30000 is 1.3428919088840485



 95%|█████████▌| 30505/32000 [23:31<01:09, 21.61it/s]

loss for 30500 is 1.3544514676332473



 97%|█████████▋| 30997/32000 [23:52<00:46, 21.63it/s]


 97%|█████████▋| 31007/32000 [23:53<00:45, 21.64it/s]

loss for 31000 is 1.3585179814100266



 98%|█████████▊| 31452/32000 [24:15<00:25, 21.61it/s]


 98%|█████████▊| 31501/32000 [24:18<00:23, 21.61it/s]

loss for 31500 is 1.3467112534046173



100%|██████████| 32000/32000 [24:39<00:00, 21.63it/s]


  0%|          | 2/32000 [00:00<33:42, 15.82it/s]

epoch 0 loss is 1.3663149062394127
per character loss is 0.015494743031290567
loss for 0 is 1.3610956805944443



  1%|▏         | 449/32000 [00:23<27:37, 19.04it/s]


  2%|▏         | 507/32000 [00:26<27:00, 19.43it/s]

loss for 500 is 1.3619913773536683



  3%|▎         | 1003/32000 [00:47<24:27, 21.12it/s]

loss for 1000 is 1.3624496586322785



  5%|▍         | 1494/32000 [01:10<24:04, 21.11it/s]


  5%|▍         | 1503/32000 [01:11<24:07, 21.06it/s]

loss for 1500 is 1.3562024517059326



  6%|▌         | 1961/32000 [01:34<24:10, 20.70it/s]


  6%|▋         | 2002/32000 [01:36<24:04, 20.76it/s]

loss for 2000 is 1.3732633123397826



  8%|▊         | 2485/32000 [01:59<23:36, 20.84it/s]


  8%|▊         | 2503/32000 [02:00<23:37, 20.82it/s]

loss for 2500 is 1.3687590728998185



  9%|▉         | 2922/32000 [02:26<24:13, 20.00it/s]


  9%|▉         | 3004/32000 [02:31<24:20, 19.85it/s]

loss for 3000 is 1.359464674949646



 11%|█         | 3442/32000 [02:57<24:29, 19.43it/s]


 11%|█         | 3503/32000 [03:01<24:33, 19.34it/s]

loss for 3500 is 1.3714992978572846



 12%|█▏        | 3918/32000 [03:27<24:47, 18.88it/s]


 13%|█▎        | 4002/32000 [03:32<24:46, 18.84it/s]

loss for 4000 is 1.358958144903183



 14%|█▍        | 4401/32000 [03:58<24:56, 18.44it/s]


 14%|█▍        | 4503/32000 [04:05<25:00, 18.33it/s]

loss for 4500 is 1.3478764013051987



 15%|█▌        | 4946/32000 [04:32<24:48, 18.17it/s]


 16%|█▌        | 5007/32000 [04:36<24:51, 18.10it/s]

loss for 5000 is 1.3554227566719055



 17%|█▋        | 5421/32000 [05:03<24:49, 17.84it/s]


 17%|█▋        | 5503/32000 [05:09<24:48, 17.80it/s]

loss for 5500 is 1.374225477695465



 18%|█▊        | 5914/32000 [05:34<24:35, 17.68it/s]


 19%|█▉        | 6004/32000 [05:39<24:29, 17.69it/s]


loss for 6000 is 1.3605900985002517


 20%|█▉        | 6374/32000 [06:04<24:25, 17.49it/s]


 20%|██        | 6504/32000 [06:10<24:10, 17.57it/s]

loss for 6500 is 1.3660223196744918



 22%|██▏       | 6958/32000 [06:35<23:45, 17.57it/s]


 22%|██▏       | 7002/32000 [06:38<23:43, 17.57it/s]

loss for 7000 is 1.3544405626058578



 23%|██▎       | 7437/32000 [07:04<23:21, 17.53it/s]


 23%|██▎       | 7503/32000 [07:07<23:16, 17.55it/s]

loss for 7500 is 1.3578645675182341



 25%|██▍       | 7903/32000 [07:32<22:59, 17.46it/s]


 25%|██▌       | 8006/32000 [07:39<22:56, 17.44it/s]

loss for 8000 is 1.345832135796547



 26%|██▋       | 8405/32000 [08:04<22:39, 17.35it/s]


 27%|██▋       | 8503/32000 [08:11<22:38, 17.29it/s]

loss for 8500 is 1.360608007311821



 28%|██▊       | 8869/32000 [08:37<22:28, 17.15it/s]


 28%|██▊       | 9005/32000 [08:44<22:19, 17.17it/s]

loss for 9000 is 1.369520151257515



 30%|██▉       | 9466/32000 [09:08<21:45, 17.25it/s]


 30%|██▉       | 9502/32000 [09:10<21:43, 17.26it/s]

loss for 9500 is 1.3639406965970993



 31%|███       | 9942/32000 [09:37<21:20, 17.23it/s]


 31%|███▏      | 10005/32000 [09:40<21:17, 17.22it/s]

loss for 10000 is 1.35714011323452



 33%|███▎      | 10442/32000 [10:05<20:49, 17.25it/s]


 33%|███▎      | 10506/32000 [10:09<20:46, 17.25it/s]

loss for 10500 is 1.3631595571041106



 34%|███▍      | 10889/32000 [10:33<20:27, 17.20it/s]


 34%|███▍      | 11007/32000 [10:39<20:20, 17.20it/s]

loss for 11000 is 1.3832003307342529



 36%|███▌      | 11413/32000 [11:05<20:00, 17.15it/s]


 36%|███▌      | 11506/32000 [11:12<19:58, 17.10it/s]

loss for 11500 is 1.3638671877384185



 37%|███▋      | 11910/32000 [11:37<19:36, 17.08it/s]


 38%|███▊      | 12000/32000 [11:41<19:29, 17.10it/s]

loss for 12000 is 1.3670747612714766



 39%|███▉      | 12427/32000 [12:05<19:03, 17.12it/s]


 39%|███▉      | 12505/32000 [12:09<18:57, 17.14it/s]

loss for 12500 is 1.3706285445690154



 41%|████      | 12995/32000 [12:33<18:21, 17.25it/s]


 41%|████      | 13004/32000 [12:33<18:20, 17.26it/s]

loss for 13000 is 1.3635444597005844



 42%|████▏     | 13488/32000 [12:56<17:46, 17.36it/s]


 42%|████▏     | 13503/32000 [12:57<17:45, 17.37it/s]

loss for 13500 is 1.3657385268211364



 44%|████▍     | 14004/32000 [13:18<17:06, 17.53it/s]

loss for 14000 is 1.3591424527168274



 45%|████▌     | 14502/32000 [13:40<16:30, 17.67it/s]

loss for 14500 is 1.3598746178150176



 47%|████▋     | 14976/32000 [14:02<15:58, 17.77it/s]


 47%|████▋     | 15003/32000 [14:04<15:56, 17.77it/s]

loss for 15000 is 1.3434483174085616



 48%|████▊     | 15427/32000 [14:27<15:31, 17.79it/s]


 48%|████▊     | 15505/32000 [14:31<15:26, 17.80it/s]

loss for 15500 is 1.3675712469816208



 50%|████▉     | 15999/32000 [14:53<14:53, 17.92it/s]


 50%|█████     | 16001/32000 [14:53<14:53, 17.92it/s]

loss for 16000 is 1.3699277737140656



 52%|█████▏    | 16482/32000 [15:16<14:22, 17.99it/s]


 52%|█████▏    | 16504/32000 [15:16<14:20, 18.00it/s]

loss for 16500 is 1.3596867324113846



 53%|█████▎    | 16967/32000 [15:39<13:52, 18.06it/s]


 53%|█████▎    | 17003/32000 [15:42<13:51, 18.04it/s]

loss for 17000 is 1.3609293894767762



 55%|█████▍    | 17495/32000 [16:05<13:20, 18.13it/s]


 55%|█████▍    | 17503/32000 [16:05<13:19, 18.13it/s]

loss for 17500 is 1.3459197615385055



 56%|█████▋    | 18000/32000 [16:28<12:48, 18.21it/s]


 56%|█████▋    | 18005/32000 [16:28<12:48, 18.22it/s]

loss for 18000 is 1.3660921384096145



 58%|█████▊    | 18507/32000 [16:49<12:16, 18.33it/s]

loss for 18500 is 1.3473121757507325



 59%|█████▉    | 18960/32000 [17:13<11:50, 18.34it/s]


 59%|█████▉    | 19003/32000 [17:15<11:48, 18.35it/s]

loss for 19000 is 1.353181417107582



 61%|██████    | 19504/32000 [17:38<11:17, 18.43it/s]

loss for 19500 is 1.3676407268047333



 63%|██████▎   | 20004/32000 [17:58<10:46, 18.54it/s]

loss for 20000 is 1.3577444494962692



 64%|██████▍   | 20504/32000 [18:20<10:16, 18.64it/s]

loss for 20500 is 1.3675628728866578



 66%|██████▌   | 21003/32000 [18:42<09:47, 18.71it/s]

loss for 21000 is 1.349142173409462



 67%|██████▋   | 21489/32000 [19:05<09:20, 18.76it/s]


 67%|██████▋   | 21506/32000 [19:06<09:19, 18.76it/s]

loss for 21500 is 1.349740507721901



 69%|██████▊   | 21957/32000 [19:29<08:54, 18.78it/s]


 69%|██████▉   | 22005/32000 [19:31<08:51, 18.79it/s]

loss for 22000 is 1.3583019040822983



 70%|███████   | 22461/32000 [19:52<08:26, 18.83it/s]


 70%|███████   | 22501/32000 [19:55<08:24, 18.82it/s]

loss for 22500 is 1.3526991139650344



 72%|███████▏  | 22999/32000 [20:17<07:56, 18.89it/s]


 72%|███████▏  | 23005/32000 [20:18<07:56, 18.89it/s]

loss for 23000 is 1.3620704629421234



 73%|███████▎  | 23480/32000 [20:41<07:30, 18.92it/s]


 73%|███████▎  | 23504/32000 [20:42<07:29, 18.92it/s]

loss for 23500 is 1.3599634963274



 75%|███████▍  | 23975/32000 [21:05<07:03, 18.95it/s]


 75%|███████▌  | 24002/32000 [21:06<07:02, 18.95it/s]

loss for 24000 is 1.3379975416660308



 76%|███████▋  | 24472/32000 [21:29<06:36, 18.98it/s]


 77%|███████▋  | 24503/32000 [21:30<06:34, 18.99it/s]

loss for 24500 is 1.3587690861225128



 78%|███████▊  | 24986/32000 [21:52<06:08, 19.04it/s]


 78%|███████▊  | 25005/32000 [21:53<06:07, 19.03it/s]

loss for 25000 is 1.343687363743782



 80%|███████▉  | 25460/32000 [22:15<05:43, 19.06it/s]


 80%|███████▉  | 25503/32000 [22:17<05:40, 19.07it/s]

loss for 25500 is 1.3532689579725266



 81%|████████  | 25992/32000 [22:40<05:14, 19.10it/s]


 81%|████████▏ | 26005/32000 [22:41<05:13, 19.10it/s]

loss for 26000 is 1.3750774309635163



 83%|████████▎ | 26502/32000 [23:04<04:47, 19.14it/s]

loss for 26500 is 1.3634148383140563



 84%|████████▍ | 27005/32000 [23:26<04:20, 19.20it/s]

loss for 27000 is 1.3499385885000228



 86%|████████▌ | 27506/32000 [23:46<03:53, 19.29it/s]

loss for 27500 is 1.3548855497837067



 88%|████████▊ | 28003/32000 [24:07<03:26, 19.35it/s]

loss for 28000 is 1.3607794595956801



 89%|████████▉ | 28464/32000 [24:29<03:02, 19.37it/s]


 89%|████████▉ | 28503/32000 [24:31<03:00, 19.36it/s]

loss for 28500 is 1.383752654194832



 91%|█████████ | 28985/32000 [24:54<02:35, 19.39it/s]


 91%|█████████ | 29001/32000 [24:54<02:34, 19.40it/s]

loss for 29000 is 1.3558809657096862



 92%|█████████▏| 29485/32000 [25:17<02:09, 19.43it/s]


 92%|█████████▏| 29503/32000 [25:18<02:08, 19.43it/s]

loss for 29500 is 1.3688066226243973



 94%|█████████▍| 30007/32000 [25:40<01:42, 19.48it/s]

loss for 30000 is 1.3385627220869065



 95%|█████████▌| 30502/32000 [26:00<01:16, 19.54it/s]

loss for 30500 is 1.3525430266857148



 97%|█████████▋| 30918/32000 [26:23<00:55, 19.53it/s]


 97%|█████████▋| 31001/32000 [26:26<00:51, 19.54it/s]


loss for 31000 is 1.357750362277031


 98%|█████████▊| 31464/32000 [26:49<00:27, 19.54it/s]


 98%|█████████▊| 31507/32000 [26:51<00:25, 19.55it/s]

loss for 31500 is 1.344699290752411



100%|█████████▉| 31965/32000 [27:14<00:01, 19.55it/s]


100%|██████████| 32000/32000 [27:16<00:00, 19.55it/s]

  0%|          | 0/32000 [00:00<?, ?it/s]

epoch 1 loss is 1.359756861652388
per character loss is 0.015420371292242961
loss for 0 is 1.3610503693819047



  2%|▏         | 504/32000 [00:23<24:09, 21.72it/s]

loss for 500 is 1.360973565340042



  3%|▎         | 984/32000 [00:46<24:32, 21.07it/s]


  3%|▎         | 1004/32000 [00:47<24:32, 21.05it/s]

loss for 1000 is 1.3617562353610992



  5%|▍         | 1466/32000 [01:11<24:47, 20.52it/s]


  5%|▍         | 1502/32000 [01:13<24:50, 20.46it/s]

loss for 1500 is 1.3566583104133605



  6%|▌         | 1986/32000 [01:36<24:12, 20.66it/s]


  6%|▋         | 2002/32000 [01:37<24:15, 20.61it/s]

loss for 2000 is 1.3748712043762208



  8%|▊         | 2473/32000 [01:59<23:50, 20.64it/s]


  8%|▊         | 2502/32000 [02:01<23:51, 20.60it/s]

loss for 2500 is 1.367979378938675



  9%|▉         | 3000/32000 [02:23<23:05, 20.93it/s]

loss for 3000 is 1.3579032872915269



 11%|█         | 3496/32000 [02:46<22:40, 20.94it/s]


 11%|█         | 3502/32000 [02:47<22:43, 20.91it/s]

loss for 3500 is 1.371278619170189



 12%|█▏        | 3986/32000 [03:10<22:20, 20.89it/s]


 13%|█▎        | 4005/32000 [03:11<22:19, 20.89it/s]

loss for 4000 is 1.3586689026355743



 14%|█▍        | 4503/32000 [03:34<21:46, 21.04it/s]

loss for 4500 is 1.3470801178216933



 16%|█▌        | 4979/32000 [03:58<21:32, 20.91it/s]


 16%|█▌        | 5006/32000 [03:59<21:31, 20.90it/s]

loss for 5000 is 1.3550323761701584



 17%|█▋        | 5462/32000 [04:23<21:19, 20.74it/s]


 17%|█▋        | 5501/32000 [04:26<21:21, 20.68it/s]

loss for 5500 is 1.3745064420700073



 18%|█▊        | 5830/32000 [04:46<21:26, 20.35it/s]

In [ ]:
# Saves the entire model under the given filename
def save_model(model,filename):
    torch.save(model, filename)
    
    return

# Saves the model parameters only (for maximum usability)

def save_model_params(model, filename):

    torch.save(model.state_dict(), filename)

    return filename

#  ideally, I could get per character loss, then I would also be able to get the total expected loss
# so: we want to get total loss, then divide it by all the length of the number of examples we saw

In [ ]:
def load_model_from_params(filename):
    model = RNN(abc.vocab_size, n_hidden, abc.vocab_size)
    model.load_state_dict(torch.load(filename))
    return model #vs return model.eval()??

In [ ]:
filename = "reddit_draft_new.pt"

if True:

    filename = save_model_params(rnn, "reddit_draft_new.pt")

In [ ]:
if True:
    eval_model = load_model_from_params(filename)
    eval_model.eval() # this is a mutating operation


In [ ]:

# returns the loss for the entire line (requires normalization for comparison)
def get_loss_on_line(rnn, line):
    input_tensor =  abc.lineToTensor([None] + [x for x in line])
    target_tensor = abc.lineToTensor([x for x in line] + ["\n"])
    criterion = nn.NLLLoss()    
    hidden = rnn.initHidden()
    loss = 0
    rnn.zero_grad()
    
    
#     print(input_tensor.size())
#     print(target_tensor[0])
#     print(target_tensor)
    for i in range(input_tensor.size()[0]):
        output, hidden = rnn(input_tensor[i], hidden)
        
        
        # had to do this simply because of how the NLLL and CrossEntropy are defined
        max_tensor = torch.argmax(target_tensor[i])
        ind = (torch.argmax(target_tensor[i])).item()
        true_target_tensor = torch.tensor([ind], dtype=torch.long)
    
#     Evaluate the loss on each character!
        loss += criterion(output, true_target_tensor)
    
    return loss.item()



In [ ]:
# out = eval_model)

# so there's a couple possibilities: we can have jim and ask to predict as well as just get the loss of the example
# out = train()
# ()
#lineToTensor

# get it as tensors, then run it, then do loss addition

STRING_TO_TEST =  "David"
print(get_loss_on_line(eval_model, STRING_TO_TEST )/len(STRING_TO_TEST ))

# we now want to implement sampling:
#  is that useful though? 
# will it be good?
# instead, we can also try and get text for the inputs 
#  then train on that, then run it on some numerical numbers

# visualization would be super useful 
# for pretty printing, we can colour the terminal output
# otherwise, we will need to somehow encode the colour so that it is output to the file
# 


In [ ]:
#  print("\x1b[31m\"red\"\x1b[0m")

# if no thresholding, then we should at least like somehow graphically display?
# no,... this is a different concern. Don't put frontend and backend together! (or visualization and etc.)


In [ ]:
from colorama import Fore

In [ ]:
# print(Fore.RED + "yoo")

# print(Fore.BLUE + "haha")

# if on average more than twice as high loss on this sample, then we should flag it for further review
THRESHOLD =  1.8332151545300774 * 2


# some more powerful model: uses LSTM as well as additional fields and operators!
# ok, so now let us just iterate the text file
with open("data\\test-cases.txt", "r") as file:
    for line in file:
        example_loss = get_loss_on_line(eval_model, line)/len(line )
        if (example_loss > THRESHOLD):
            print(Fore.RED + line)
        else:
            print(Fore.BLUE + line)
        
        print("loss" + str(example_loss))
    
# perhaps we should train on google news corpus for a little while..
# this 
    

In [ ]:
import nltk

In [ ]:
from nltk.corpus import reuters

In [ ]:
print("ok")

sentences = reuters.raw().splitlines()
# print(reuters.raw())


In [ ]:
print(type(sentences))
print(len(sentences))

In [ ]:

# these are not exactly tokenized on sentences; but that is OK!
sentences[:100]

with open("reuters_news.txt", "w") as file:
    file.write(reuters.raw())

In [ ]:
# we need a smaller dataset for development
# so, let's cut up the reuters into smaller (for example, load just the first K bytes of the file.)
import time

def make_proto_dataset(size):
    with open("reuters_news_{}.txt".format(size), "w") as file:
        
        
        file.write('\n'.join(reuters.raw().splitlines()[0:size]))
    print("file created with {} lines".format(size))
        


In [ ]:
#     the question now is how many neurons and the architecture to use
# we can also look into enhancement with the tqdm inside the object?
start = time.time()


make_proto_dataset(10000)
elapsed = time.time() - start
print("elapsed time is {}".format(elapsed ))


In [ ]:
# reuters dataset has umlauts and other non-standard characters, so we should try and account for that! 
# also: we should try and do a sort of full merge: merge between the train dataset and test dataset vocabs
# other than that, we can just apply a regularizer to both sets, to get out the processed data
# for now, let's just apply a regularization

start = time.time()
reuters_dataset = TextDataset( "reuters_news_10000.txt", True)
elapsed = time.time() - start
print("elapsed time is {}".format(elapsed ))

# jeez, so it takes more than 8 minutes to create the dataset!

In [ ]:
print(len(reuters_dataset))
from tqdm import tqdm
def general_train_function(dataset):
# del rnn
# rnn = RNN(abc.vocab_size, n_hidden, abc.vocab_size)

    epoch_loss = 0
    # loss every k iters
    # 
    loss_per_k = 0
    
    total_loss = 0
    total_length  = 0
    epoch_length = 0


    num_epochs = 10
    
    for k in range(num_epochs ):

        for i,(x,y) in enumerate(tqdm(dataset)):
        #     print(x)
        #     print(x)
        #     print(y)
            _, loss = train(x,y)
            epoch_loss += loss
            epoch_length += x.size()[0]
            total_loss += loss
            total_length += x.size()[0]
            loss_per_k += loss
        #     print(i)
        #     abc = i
        
            # for the first 100 iters, print the loss of every line!
#             if i < 100:
#                 print ("loss for {} is {}".format(i,epoch_loss/(i+1)))
                
            
            if i % 100 == 0 and i != 0:
                print ("loss for {} is {}".format(i,loss_per_k/100))
                loss_per_k = 0
                

        print("epoch {} loss is {}".format(k, epoch_loss/i))
        print("per character loss is {}".format(epoch_loss/epoch_length))
        epoch_loss = 0
        epoch_length = 0
#     ideally: we would be able to compute the quintile losses
    

In [ ]:

# WE NEED THIS LINE TO RESET THE RNN!!
rnn = RNN(reuters_dataset.vocab_size, 512, reuters_dataset.vocab_size)
learning_rate = 0.0005 # If you set this too high, it might explode. If too low, it might not learn
#  we had to set it a big lower to force convergence

import torch.optim as optim
optimizer = optim.SGD(rnn.parameters(), lr = 0.0001)

# returns the loss for a line

def general_train(input_tensor, target_tensor):
    
        
    
    optimizer.zero_grad()
    
#     print (input_tensor)
    
#     print("changed3")
#     print(input_tensor[1])
    criterion = nn.NLLLoss()    
    hidden = rnn.initHidden()
    loss = 0
    rnn.zero_grad()
#     print(input_tensor.size())
#     print(target_tensor[0])
#     print(target_tensor)
    for i in range(input_tensor.size()[0]):
        output, hidden = rnn(input_tensor[i], hidden)
        
        
        
#         find where the one is:
# 
#         torch.tensor([all_categories.index(category)], dtype=torch.long)
        max_tensor = torch.argmax(target_tensor[i])
#         print(max_tensor)
        ind = (torch.argmax(target_tensor[i])).item()
#         print("this the target")
#         print(target_tensor[i])
#         print(ind)
        true_target_tensor = torch.tensor([ind], dtype=torch.long)
    
#     Evaluate the loss on each character!
        loss += criterion(output, true_target_tensor)
        
#         expects JUST a single target class:

#     print ("loss for i " + str(loss.item()))    
#         print()
# should be do the loss on each thing, or each batch! no, we should accumulate it! 

    loss.backward()
    optimizer.step()
    # Add parameters' gradients to their values, multiplied by learning rate
#     for p in rnn.parameters():
#         p.data.add_(-learning_rate, p.grad.data)

    return output, loss.item()

# why not run this just on all the tensors!! 

# then, we just call it with the dataset class, and then just iterate everything!!

In [ ]:
general_train_function(reuters_dataset)
# perhaps: examine the gradient instead!



In [ ]:

# returns the loss for a line, evaluating on a BASIC rnn, and using the provided optimizer
def prototype_general_train(input_tensor, target_tensor, basic_rnn, optimizer):
    
        
    
    optimizer.zero_grad()
    
    criterion = nn.NLLLoss()    
    hidden = rnn.initHidden()
    loss = 0
    basic_rnn.zero_grad()
    for i in range(input_tensor.size()[0]):
        output, hidden = basic_rnn(input_tensor[i], hidden)
        
        max_tensor = torch.argmax(target_tensor[i])
        ind = (torch.argmax(target_tensor[i])).item()
        true_target_tensor = torch.tensor([ind], dtype=torch.long)
        #     Evaluate the loss on each character!
        loss += criterion(output, true_target_tensor)
        
    loss.backward()
    optimizer.step()

    return output, loss.item()
